### ISSUE TITLE
[Extra Chat] Unable to Register Character 

### ISSUE THREAD

**Issue by Pyresque** [anna-is-cute/plugin-issues#106]
Hello.

[I'm having the same issue as described in here,](https://github.com/anna-is-cute/plugin-issues/issues/100) down to the same details. As in, after clicking "Register [Character Name]" it says "Retrieving Challenge" and "Waiting", and then returns back to the "Register Character" screen and I can no longer click on any of the buttons to try to register again. This is happening after a clean install of XIV, Dalamud and all plugins on a new computer, since my old one broke down--worthy of note is that I already had an ExtraChat account before, so this isn't my first time trying to authenticate.

Also of note is that my home world is Golem, on Dynamis (one of the four new worlds added pre-DT). Previously it was Marilith, also on Dynamis, and before *that* it was Adamantoise, on Aether. [I had an issue upon transferring to Marilith back in 2022 that I posted here before](https://github.com/anna-is-cute/plugin-issues/issues/34). I'm wondering if I'm having issue now because I transferred to Golem, and maybe ExtraChat needs an update for those four new servers?

Here's some console info if it helps, it's what shows when the issue happens:

```
16:57:13.508 | ERR | [ExtraChat] Error in client loop
	System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
	 ---> System.IO.IOException: Unable to read data from the transport connection: A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo..
	 ---> System.Net.Sockets.SocketException (995): A operação de E/S foi anulada devido a uma saída de thread ou a uma requisição de aplicativo.
	   --- End of inner exception stack trace ---
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
	   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
	   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.Http.HttpConnection.ReadBufferedAsyncCore(Memory`1 destination)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.Http.HttpConnection.RawConnectionStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.IO.Stream.ReadAtLeastAsyncCore(Memory`1 buffer, Int32 minimumBytes, Boolean throwOnEndOfStream, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
	   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
	   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
	--- End of stack trace from previous location ---
	   at ExtraChat.Ext.ReceiveMessage(ClientWebSocket client) in /work/repo/client/ExtraChat/Ext.cs:line 24
	   at ExtraChat.Client.Loop() in /work/repo/client/ExtraChat/Client.cs:line 588
	   at ExtraChat.Client.<StartLoop>b__43_0() in /work/repo/client/ExtraChat/Client.cs:line 98
16:57:14.509 | INF | [LOCALPLUGIN] Finished unloading "ExtraChat"
16:57:14.509 | INF | [LOCALPLUGIN] Loading ExtraChat.dll
16:57:14.728 | INF | [LOCALPLUGIN] Finished loading "ExtraChat"
16:57:18.457 | ERR | [ExtraChat] Error in client loop
	System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
	   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
	   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
	   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
	   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
	   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
	--- End of stack trace from previous location ---
	   at ExtraChat.Ext.ReceiveMessage(ClientWebSocket client) in /work/repo/client/ExtraChat/Ext.cs:line 24
	   at ExtraChat.Client.Loop() in /work/repo/client/ExtraChat/Client.cs:line 588
	   at ExtraChat.Client.<StartLoop>b__43_0() in /work/repo/client/ExtraChat/Client.cs:line 98
```

**Comment by shad0wshayd3** [comment]
I'm getting the same behavior when trying to register, the same client loop errors in my log, and am on Rafflesia.

**Comment by Dubsys** [comment]
Same issue

![image](https://github.com/user-attachments/assets/aaaa4cb8-31c3-4357-a076-20de9286aa9c)

**Comment by Dubsys** [comment]
I forgot the dev doesn't actually care about their plugins, unfortunate.

**Comment by anna-is-cute** [comment]
Just a reminder that posting abusive comments about me while I am out of town and thought this issue had been fixed is an effective way to make me purposely not fix it.

**Comment by shad0wshayd3** [comment]
Whatever that guy has going on might be different, I was able to register on Rafflesia about a month ago and it's been working fine since across a couple of DCs.

**Comment by anna-is-cute** [comment]
That person most likely has their profile set to private, so Extra Chat is unable to verify their account. If they fix that and the issue persists, they can open a new issue (maybe, not sure if GitHub will let them after I blocked them).
